# Generated by Django 5.0.6 on 2024-07-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_checkout_checkoutproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutproduct',
            old_name='Checkout',
            new_name='checkout',
        ),
    ]
