# Generated by Django 5.0.6 on 2024-07-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_contact_newslatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('pic', models.ImageField(upload_to='upload/testimonial')),
            ],
        ),
    ]
